export const financingBySectorData = [
  { sector: "Renewable Energy", financing: 12500000 },
  { sector: "Water Management", financing: 8200000 },
  { sector: "Waste Management", financing: 6800000 },
  { sector: "Healthcare", financing: 9100000 },
  { sector: "Education", financing: 5300000 },
  { sector: "Smart Agriculture", financing: 3300000 },
];

export const financingByCompanySizeData = [
    { companySize: "Micro", financing: 4000000 },
    { companySize: "Small", financing: 15000000 },
    { companySize: "Medium", financing: 20000000 },
    { companySize: "Large", financing: 6200000 },
];

export const COLORS = ["#0056b3", "#007bff", "#F39C12", "#8E44AD", "#2ECC71"];

const projectsForClient1 = [
    {
      id: 101,
      purposeOfFinancing: "Solar panel installation for factory roof",
      totalFinancingAmount: 3500000,
      amountUsed: 3500000,
      currency: "EGP",
      typeOfFacility: "Long term",
      facilityClassification: "Performing",
      usageType: "New Facility",
      dateOfCreditApproval: new Date("2023-05-15"),
      fundedUnderInitiative: "GEFF",
      environmentalConsultantUsed: true,
      sustainabilityAxis: "Renewable Energy",
      environmentalSocialClassification: "Environmental",
      classificationMethod: "Specific project type",
      impactIndicators: "Reduce CO2 emissions by 500 tons/year",
      status: "Completed",
    },
    {
      id: 102,
      purposeOfFinancing: "Upgrade to energy-efficient lighting system",
      totalFinancingAmount: 1500000,
      amountUsed: 1200000,
      currency: "EGP",
      typeOfFacility: "Medium term",
      facilityClassification: "Performing",
      usageType: "Existing Used",
      dateOfCreditApproval: new Date("2024-01-20"),
      fundedUnderInitiative: "",
      environmentalConsultantUsed: false,
      sustainabilityAxis: "Renewable Energy",
      environmentalSocialClassification: "Environmental",
      classificationMethod: "Specific project type",
      impactIndicators: "Reduce electricity consumption by 20%",
      status: "Active",
    },
];

const projectsForClient2 = [
    {
        id: 201,
        purposeOfFinancing: "Wastewater treatment plant",
        totalFinancingAmount: 1200000,
        amountUsed: 1200000,
        currency: "EGP",
        typeOfFacility: "Long term",
        facilityClassification: "Performing",
        usageType: "New Facility",
        dateOfCreditApproval: new Date("2022-11-10"),
        fundedUnderInitiative: "EPAP",
        environmentalConsultantUsed: true,
        sustainabilityAxis: "Water Management",
        environmentalSocialClassification: "Environmental",
        classificationMethod: "Specific project type",
        impactIndicators: "Treat 10,000 m³ of wastewater annually",
        status: "Completed",
    }
];


export const mockClientData = [
  { 
    id: 1, 
    companyName: "GreenTech Solutions", 
    sector: "Private",
    unifiedCommercialRegNo: "123456789012345678", 
    companyType: "Industrial", 
    companySize: "Medium", 
    isicCodeL4: "3510",
    contactPerson: "Ahmed Ali", 
    contactEmail: "ahmed.ali@greentech.com",
    projects: projectsForClient1,
  },
  { 
    id: 2, 
    companyName: "AquaPure Ltd.", 
    sector: "Private",
    unifiedCommercialRegNo: "234567890123456789", 
    companyType: "Service", 
    companySize: "Small", 
    isicCodeL4: "3600",
    contactPerson: "Fatima Zahra", 
    contactEmail: "fatima.zahra@aquapure.com",
    projects: projectsForClient2,
  },
  { 
    id: 3, 
    companyName: "BioWaste Corp.", 
    sector: "Private",
    unifiedCommercialRegNo: "345678901234567890", 
    companyType: "Industrial", 
    companySize: "Large", 
    isicCodeL4: "3821",
    contactPerson: "Khaled Hassan", 
    contactEmail: "khaled.hassan@biowaste.com",
    projects: [],
  },
  { 
    id: 4, 
    companyName: "EduVantage", 
    sector: "Private",
    unifiedCommercialRegNo: "456789012345678901", 
    companyType: "Service", 
    companySize: "Medium", 
    isicCodeL4: "8549",
    contactPerson: "Nour Mohamed", 
    contactEmail: "nour.mohamed@eduvantage.com",
    projects: [],
  },
  { 
    id: 5, 
    companyName: "AgriInnovate Farms", 
    sector: "Private",
    unifiedCommercialRegNo: "567890123456789012", 
    companyType: "Contractor", 
    companySize: "Small",
    isicCodeL4: "0161", 
    contactPerson: "Youssef Ibrahim", 
    contactEmail: "youssef.ibrahim@agriinnovate.com",
    projects: [],
  },
  { 
    id: 6, 
    companyName: "MediCare Hospitals", 
    sector: "Public",
    unifiedCommercialRegNo: "678901234567890123", 
    companyType: "Service", 
    companySize: "Large", 
    isicCodeL4: "8610",
    contactPerson: "Mariam El-Masry", 
    contactEmail: "mariam.elmasry@medicare.com",
    projects: [],
  },
];
