
export const environmentalSectorsData = [
  { sector: "Renewable Energy", financing: 110000000 },
  { sector: "Water Management", financing: 48000000 },
  { sector: "Waste Management", financing: 21000000 + 42000000 },
  { sector: "Smart Agriculture", financing: 36000000 + 55000000 },
];

export const socialSectorsData = [
  { sector: "Healthcare", financing: 500000000 + 350000000 },
  { sector: "Education", financing: 220000000 + 180000000 },
];

export const industrialSectorsData = [
    { sector: "Electricity", financing: 75000000 },
    { sector: "Cement", financing: 82000000 },
    { sector: "Fertilizers", financing: 30000000 },
    { sector: "Steel", financing: 68000000 + 95000000 },
    { sector: "Aluminum", financing: 25000000 },
    { sector: "Green Hydrogen", financing: 10000000 },
];

export const financingByCompanySizeData = [
    { companySize: "Small", financing: 124000000 + 55000000 },
    { companySize: "Medium", financing: 350000000 + 42000000 + 180000000 },
    { companySize: "Large", financing: 642000000 + 350000000 + 95000000 },
];

export const financingBySustainabilityType = [
  { type: "Environmental", financing: 415000000 + 42000000 + 55000000 + 95000000 },
  { type: "Social", financing: 720000000 + 350000000 + 180000000 },
]

export const financingByCbamData = [
  { type: "CBAM Affected", financing: 550000000 + 95000000 },
  { type: "Not Affected", financing: 585000000 + 42000000 + 55000000 + 350000000 + 180000000},
];

export const COLORS = ["#0056b3", "#007bff", "#F39C12", "#8E44AD", "#2ECC71", "#d35400"];

const projectsForClient1 = [
    {
      id: 101,
      purposeOfFinancing: "تركيب ألواح شمسية لسقف المصنع",
      totalFinancingAmount: 75000000,
      amountUsed: 75000000,
      currency: "جنيه مصري",
      typeOfFacility: "طويل الأجل",
      facilityClassification: "عامل",
      usageType: "تسهيل جديد",
      dateOfCreditApproval: new Date("2023-05-15"),
      fundedUnderInitiative: "GEFF",
      environmentalConsultantUsed: true,
      sustainabilityAxis: "الطاقة المتجددة",
      environmentalSocialClassification: "بيئي",
      classificationMethod: "نوع المشروع المحدد",
      impactIndicators: "تقليل انبعاثات ثاني أكسيد الكربون بمقدار 500 طن/سنة",
      status: "مكتمل",
    },
    {
      id: 102,
      purposeOfFinancing: "تحديث نظام الإضاءة إلى نظام موفر للطاقة",
      totalFinancingAmount: 35000000,
      amountUsed: 22000000,
      currency: "جنيه مصري",
      typeOfFacility: "متوسط الأجل",
      facilityClassification: "عامل",
      usageType: "مستخدم حالي",
      dateOfCreditApproval: new Date("2024-01-20"),
      fundedUnderInitiative: "",
      environmentalConsultantUsed: false,
      sustainabilityAxis: "الطاقة المتجددة",
      environmentalSocialClassification: "بيئي",
      classificationMethod: "نوع المشروع المحدد",
      impactIndicators: "تقليل استهلاك الكهرباء بنسبة 20٪",
      status: "نشيط",
    },
];

const projectsForClient2 = [
    {
        id: 201,
        purposeOfFinancing: "محطة معالجة مياه الصرف الصحي",
        totalFinancingAmount: 48000000,
        amountUsed: 48000000,
        currency: "جنيه مصري",
        typeOfFacility: "طويل الأجل",
        facilityClassification: "عامل",
        usageType: "تسهيل جديد",
        dateOfCreditApproval: new Date("2022-11-10"),
        fundedUnderInitiative: "EPAP",
        environmentalConsultantUsed: true,
        sustainabilityAxis: "إدارة المياه",
        environmentalSocialClassification: "بيئي",
        classificationMethod: "نوع المشروع المحدد",
        impactIndicators: "معالجة 10,000 متر مكعب من مياه الصرف الصحي سنويًا",
        status: "مكتمل",
    }
];

const projectsForClient3 = [
    {
        id: 301,
        purposeOfFinancing: "تطوير مصنع الاسمنت لتقليل الانبعاثات",
        totalFinancingAmount: 82000000,
        amountUsed: 40000000,
        currency: "جنيه مصري",
        typeOfFacility: "طويل الأجل",
        facilityClassification: "عامل",
        usageType: "تسهيل جديد",
        dateOfCreditApproval: new Date("2024-02-10"),
        fundedUnderInitiative: "CBAM Fund",
        environmentalConsultantUsed: true,
        sustainabilityAxis: "الطاقة المتجددة",
        environmentalSocialClassification: "بيئي",
        classificationMethod: "نشاط الشركة",
        impactIndicators: "تقليل استهلاك الطاقة بنسبة 15%",
        status: "نشيط",
    }
];

const projectsForClient4 = [
    {
        id: 401,
        purposeOfFinancing: "تجهيز مدارس بالتكنولوجيا الحديثة",
        totalFinancingAmount: 220000000,
        amountUsed: 150000000,
        currency: "جنيه مصري",
        typeOfFacility: "متوسط الأجل",
        facilityClassification: "عامل",
        usageType: "تسهيل جديد",
        dateOfCreditApproval: new Date("2023-08-15"),
        fundedUnderInitiative: "CBE Education Initiative",
        environmentalConsultantUsed: false,
        sustainabilityAxis: "التعليم",
        environmentalSocialClassification: "اجتماعي",
        classificationMethod: "نوع المشروع المحدد",
        impactIndicators: "توفير أجهزة لوحية لـ 1000 طالب",
        status: "نشيط",
    }
];

const projectsForClient5 = [
    {
        id: 501,
        purposeOfFinancing: "تطبيق أنظمة الري الذكي",
        totalFinancingAmount: 36000000,
        amountUsed: 36000000,
        currency: "جنيه مصري",
        typeOfFacility: "متوسط الأجل",
        facilityClassification: "عامل",
        usageType: "مستخدم حالي",
        dateOfCreditApproval: new Date("2023-03-22"),
        fundedUnderInitiative: "",
        environmentalConsultantUsed: true,
        sustainabilityAxis: "الزراعة الذكية",
        environmentalSocialClassification: "بيئي",
        classificationMethod: "نوع المشروع المحدد",
        impactIndicators: "توفير 40% من استهلاك مياه الري",
        status: "مكتمل",
    }
];


const projectsForClient6 = [
    {
        id: 601,
        purposeOfFinancing: "بناء جناح مستشفى جديد",
        totalFinancingAmount: 500000000,
        amountUsed: 200000000,
        currency: "جنيه مصري",
        typeOfFacility: "طويل الأجل",
        facilityClassification: "عامل",
        usageType: "تسهيل جديد",
        dateOfCreditApproval: new Date("2023-09-01"),
        fundedUnderInitiative: "CBE Health Initiative",
        environmentalConsultantUsed: false,
        sustainabilityAxis: "الصحة",
        environmentalSocialClassification: "اجتماعي",
        classificationMethod: "نوع المشروع المحدد",
        impactIndicators: "زيادة سعة المستشفى بمقدار 50 سريرًا",
        status: "نشيط",
    }
];

const projectsForClient7 = [
    {
      id: 701,
      purposeOfFinancing: "إنشاء مرفق لإعادة تدوير المخلفات الصلبة",
      totalFinancingAmount: 42000000,
      amountUsed: 42000000,
      currency: "جنيه مصري",
      typeOfFacility: "طويل الأجل",
      facilityClassification: "عامل",
      usageType: "تسهيل جديد",
      dateOfCreditApproval: new Date("2022-08-25"),
      fundedUnderInitiative: "EPAP",
      environmentalConsultantUsed: true,
      sustainabilityAxis: "المخلفات",
      environmentalSocialClassification: "بيئي",
      classificationMethod: "نوع المشروع المحدد",
      impactIndicators: "إعادة تدوير 5000 طن من المخلفات سنوياً",
      status: "مكتمل",
    },
];

const projectsForClient8 = [
    {
      id: 801,
      purposeOfFinancing: "تمويل زراعة المحاصيل العضوية",
      totalFinancingAmount: 55000000,
      amountUsed: 25000000,
      currency: "جنيه مصري",
      typeOfFacility: "متوسط الأجل",
      facilityClassification: "عامل",
      usageType: "مستخدم حالي",
      dateOfCreditApproval: new Date("2024-03-10"),
      fundedUnderInitiative: "",
      environmentalConsultantUsed: true,
      sustainabilityAxis: "الزراعة الذكية",
      environmentalSocialClassification: "بيئي",
      classificationMethod: "نشاط الشركة",
      impactIndicators: "زيادة إنتاج المحاصيل العضوية بنسبة 30%",
      status: "نشيط",
    },
];

const projectsForClient9 = [
    {
        id: 901,
        purposeOfFinancing: "شراء أجهزة طبية حديثة للمستشفى",
        totalFinancingAmount: 350000000,
        amountUsed: 350000000,
        currency: "جنيه مصري",
        typeOfFacility: "طويل الأجل",
        facilityClassification: "عامل",
        usageType: "تسهيل جديد",
        dateOfCreditApproval: new Date("2023-01-15"),
        fundedUnderInitiative: "CBE Health Initiative",
        environmentalConsultantUsed: false,
        sustainabilityAxis: "الصحة",
        environmentalSocialClassification: "اجتماعي",
        classificationMethod: "نوع المشروع المحدد",
        impactIndicators: "توفير خدمات تشخيصية لـ 10,000 مريض إضافي سنوياً",
        status: "مكتمل",
    },
    {
        id: 902,
        purposeOfFinancing: "توسيع الفصول الدراسية وبناء مختبرات",
        totalFinancingAmount: 180000000,
        amountUsed: 90000000,
        currency: "جنيه مصري",
        typeOfFacility: "متوسط الأجل",
        facilityClassification: "عامل",
        usageType: "مستخدم حالي",
        dateOfCreditApproval: new Date("2024-04-01"),
        fundedUnderInitiative: "CBE Education Initiative",
        environmentalConsultantUsed: false,
        sustainabilityAxis: "التعليم",
        environmentalSocialClassification: "اجتماعي",
        classificationMethod: "نوع المشروع المحدد",
        impactIndicators: "زيادة استيعاب الطلاب بنسبة 25%",
        status: "نشيط",
    }
];

const projectsForClient10 = [
    {
        id: 1001,
        purposeOfFinancing: "تحديث أفران مصنع الحديد والصلب",
        totalFinancingAmount: 95000000,
        amountUsed: 50000000,
        currency: "جنيه مصري",
        typeOfFacility: "طويل الأجل",
        facilityClassification: "عامل",
        usageType: "تسهيل جديد",
        dateOfCreditApproval: new Date("2024-05-20"),
        fundedUnderInitiative: "CBAM Fund",
        environmentalConsultantUsed: true,
        sustainabilityAxis: "الطاقة المتجددة",
        environmentalSocialClassification: "بيئي",
        classificationMethod: "نشاط الشركة",
        impactIndicators: "تقليل الانبعاثات الكربونية بنسبة 20%",
        status: "نشيط",
    }
];


export const mockClientData = [
  { 
    id: 1, 
    companyName: "Green Tech Solutions", 
    sector: "خاص",
    unifiedCommercialRegNo: "123456789012345678", 
    companyType: "صناعي", 
    companySize: "متوسط", 
    isicCodeL4: "3510",
    exportsProducts: true,
    transportsToEu: true,
    contactPerson: "أحمد علي", 
    contactEmail: "ahmed.ali@greentech.com",
    projects: projectsForClient1,
  },
  { 
    id: 2, 
    companyName: "Aqua Pure Ltd.", 
    sector: "خاص",
    unifiedCommercialRegNo: "234567890123456789", 
    companyType: "خدمي", 
    companySize: "صغير", 
    isicCodeL4: "3600",
    exportsProducts: false,
    transportsToEu: false,
    contactPerson: "فاطمة الزهراء", 
    contactEmail: "fatima.zahra@aquapure.com",
    projects: projectsForClient2,
  },
  { 
    id: 3, 
    companyName: "Bio-Waste Company", 
    sector: "خاص",
    unifiedCommercialRegNo: "345678901234567890", 
    companyType: "صناعي", 
    companySize: "كبير", 
    isicCodeL4: "2011",
    exportsProducts: true,
    transportsToEu: false,
    contactPerson: "خالد حسن", 
    contactEmail: "khaled.hassan@biowaste.com",
    projects: projectsForClient3,
  },
  { 
    id: 4, 
    companyName: "Edu-Vantage", 
    sector: "خاص",
    unifiedCommercialRegNo: "456789012345678901", 
    companyType: "خدمي", 
    companySize: "متوسط", 
    isicCodeL4: "8549",
    exportsProducts: false,
    transportsToEu: false,
    contactPerson: "نور محمد", 
    contactEmail: "nour.mohamed@eduvantage.com",
    projects: projectsForClient4,
  },
  { 
    id: 5, 
    companyName: "Agri-Innovate Farms", 
    sector: "خاص",
    unifiedCommercialRegNo: "567890123456789012", 
    companyType: "مقاول", 
    companySize: "صغير",
    isicCodeL4: "0161", 
    exportsProducts: true,
    transportsToEu: false,
    contactPerson: "يوسف إبراهيم", 
    contactEmail: "youssef.ibrahim@agriinnovate.com",
    projects: projectsForClient5,
  },
  { 
    id: 6, 
    companyName: "Medicare Hospitals", 
    sector: "عام",
    unifiedCommercialRegNo: "678901234567890123", 
    companyType: "خدمي", 
    companySize: "كبير", 
    isicCodeL4: "8610",
    exportsProducts: false,
    transportsToEu: false,
    contactPerson: "مريم المصري", 
    contactEmail: "mariam.elmasry@medicare.com",
    projects: projectsForClient6,
  },
  { 
    id: 7, 
    companyName: "Recycle Co.", 
    sector: "خاص",
    unifiedCommercialRegNo: "789012345678901234", 
    companyType: "صناعي", 
    companySize: "متوسط", 
    isicCodeL4: "3830",
    exportsProducts: true,
    transportsToEu: false,
    contactPerson: "علي محمود", 
    contactEmail: "ali.mahmoud@recycleco.com",
    projects: projectsForClient7,
  },
  { 
    id: 8, 
    companyName: "Organic Fields", 
    sector: "خاص",
    unifiedCommercialRegNo: "890123456789012345", 
    companyType: "مقاول", 
    companySize: "صغير", 
    isicCodeL4: "0128",
    exportsProducts: true,
    transportsToEu: true,
    contactPerson: "سارة عبد الله", 
    contactEmail: "sara.abdullah@organicfields.com",
    projects: projectsForClient8,
  },
  { 
    id: 9, 
    companyName: "Health & Education Foundation", 
    sector: "عام",
    unifiedCommercialRegNo: "901234567890123456", 
    companyType: "خدمي", 
    companySize: "كبير", 
    isicCodeL4: "8690",
    exportsProducts: false,
    transportsToEu: false,
    contactPerson: "محمد فتحي", 
    contactEmail: "mohamed.fathy@he-foundation.com",
    projects: projectsForClient9,
  },
  { 
    id: 10, 
    companyName: "National Steel Industries", 
    sector: "عام",
    unifiedCommercialRegNo: "012345678901234567", 
    companyType: "صناعي", 
    companySize: "كبير", 
    isicCodeL4: "2410",
    exportsProducts: true,
    transportsToEu: true,
    contactPerson: "هبة شريف", 
    contactEmail: "heba.sherif@nationalsteel.com",
    projects: projectsForClient10,
  },
];
